### ISSUE TITLE
Update to handle multiple CML client library versions

### ISSUE THREAD

**Issue by jasonking3** [CiscoDevNet/sdwan-devops#94]
We could use a way to specify which CML client library version to use when running playbooks.  Currently it is set statically in the requirements.txt file and will break when targeting different CML 2.x minor versions (like we do in CI currently).

**Comment by jlothian** [comment]
What I've done so far is just create 2 different container images, and I have a different shell script for each version that call the correct container.  Determining it at runtime and loaded the correct library I think will be difficult.
